### PR TITLE
fix: segment not logging in prod

### PR DESCRIPTION
**Pull request by fbwoolf**
This PR should fix Segment in production 🤞 . Moved rendering the snippet into the `_document`. Now able to use the node env var w/out the `NEXT_PUBLIC_` syntax which would expose the write key in the browser.

Issue #571

### CODE REVIEW

**Comment by fbwoolf** [comment]
Build failure here is an active issue in webpack and in next tracked here:
https://github.com/webpack/webpack/issues/14532
https://github.com/vercel/next.js/issues/30078

Last suggestion is to downgrade node to 16 in the Dockerfile.

**Comment by fbwoolf** [comment]
@CharlieC3 I got the build passing now if you want to test/approve.

**Comment by CharlieC3** [comment]
@fbwoolf I believe you're able to deploy to staging. Once you do we can see if it works 🤞 
https://github.com/hirosystems/explorer/actions/runs/1400138068

**Comment by fbwoolf** [comment]
> @fbwoolf I believe you're able to deploy to staging. Once you do we can see if it works 🤞 https://github.com/hirosystems/explorer/actions/runs/1400138068

Nope, not logging and Segment script is not in the header. Anything that would be different w/ staging vs production?

**Comment by CharlieC3** [comment]
@fbwoolf I found an issue with the previous deployment caused by the GH org change. It should be fixed now for future staging deployments, but I had to manually deploy this branch. We'll encounter this issue for prod as well, so I may need to perform the next prod deployment.

When you get a chance can you try it again? `fix-segment-prod` is running _without_ the `SEGMENT_WRITE_KEY` env var set.

**Comment by fbwoolf** [comment]
> 
> When you get a chance can you try it again? `fix-segment-prod` is running _without_ the `SEGMENT_WRITE_KEY` env var set.

Didn't see this and was waiting to deploy again with a change I made, so your fix is likely what got it working I guess. Funny. Anyway, it is working now.

**Comment by CharlieC3** [comment]
Still a great success! Also I think the next deployment to `prod` should work now without intervention. I had to push up `1.17.2` to our new `hirosystems` Docker org .

**Review by CharlieC3 — APPROVED** [review]
:shipit:

**Comment by fbwoolf** [comment]
Thanks, @CharlieC3 for all your help!

**Comment by pkellner** [comment]
Thanks for posting this fix. I guess I need to start locking my alpine version to make sure my builds don't crash down the road for infrequently built apps.

**Pull request merged**
