### PR TITLE
feat: show receipt time on transaction page

### PR DESCRIPTION
**Pull request by dragnoir**
Close [#1030](https://github.com/hirosystems/explorer/issues/1030)

On the transaction details page, for pending transactions (mempool), I added a new component for receipt time labeled "Broadcasted"

Capture d'écran 2023-07-07 233318

### CODE REVIEW

**Review by andresgalante — CHANGES_REQUESTED** [review]
@dragnoir, thanks for the contribution! This is great!

After running your branch, I see an alignment issue where the time doesn't align with the other items at the top, since it has a `margin-left: 16px`

Can you review that, please?

@He1DAr can you take a look at this this one, please?

**Comment by dragnoir** [comment]
Thank you @andresgalante, margin left 16px removed

**Review by andresgalante — APPROVED** [review]
@dragnoir excellent! Thanks for the change!

🙏 Please squash your commits

This PR is good from my side. I'll let @He1DAr review and merge it.

**Comment by He1DAr** [comment]
Awesome @dragnoir! Please fix linting so that we can proceed with shipping it.

**Comment by He1DAr** [comment]
Also, wondering if you could add a snapshot test for src/app/txid/[txid]/TxDetails/Broadcasted.tsx. This would be amazing!

**Pull request merged**
