### PR TITLE
feat: assigned $0 for 0 STX

### PR DESCRIPTION
**Pull request by shamim-io**
closes https://github.com/hirosystems/explorer/issues/879

Closes [ Show 0 USD when balance is 0STX #879 ]

Feature details
Assigned $0 for 0 STX

File changed
`utils.ts`

### CODE REVIEW

**Comment by andresgalante** [comment]
@shamim-io I would like to know if this has been fixed since I can't reproduce it on the prod Explorer.

This is an account with `0 STX` balance and shows `$0.00` https://explorer.hiro.so/address/SP9ZK4GG9BT6JDZJ7Q8NPY7PKRYGMPMCVPPWCSXN?chain=mainnet

On your branch, the same address comes as `$0`.

🤔 Do you have an address for an example where it says `$0.01`?

**Comment by He1DAr** [comment]
Hi @shamim-io! Thank you for submitting this PR, could you please fix linting so we can proceed with merging?

**Comment by shamim-io** [comment]
@He1DAr fixed the lint. Thanks!

**Comment by He1DAr** [comment]
confirmed that it has been already fixed

**Pull request closed without merging**
