### PR TITLE
fix: make action buttons from TxListTabs semantic and aligned

### PR DESCRIPTION
**Pull request by raphaeljp**
Fixes https://github.com/hirosystems/explorer/issues/1188

### CODE REVIEW

**Review by yashhhguptaaa — APPROVED** [review]
Thanks @andresgalante for offering me to review the PR.
LGTM

**Review by andresgalante — APPROVED** [review]
Thanks @raphaeljp !! 🎉  great contribution!

@He1DAr I build this branch, and it should be ok. 

Please, when you have a min give it a try and ship it

**Comment by He1DAr** [comment]
@raphaeljp Awesome work, thank you for the PR! Can you please fix the Commitlint checks? Also, the dark mode has less contrast which may affect accessibility.
Before:
image
After:
image

**Comment by andresgalante** [comment]
@raphaeljp please make sure to squash your commits with the next change so we are able to merge this PR

**Review by He1DAr — APPROVED** [review]

**Comment by He1DAr** [comment]
LGTM! We can ship once Commitlint is fixed.

**Comment by He1DAr** [comment]
@raphaeljp could you please squish all commits into 1 commit with a message: `fix: make action buttons from TxListTabs semantic and aligned`?

**Pull request merged**
