### PR TITLE
Fix/Result not showing correctly

### PR DESCRIPTION
**Pull request by shamim-io**
Closes [ Result not showing correctly #1138 ]
Fixes issue: Result not showing correctly

Feature details
Added correct variable.

Image after fix:
Screenshot 2023-05-18 at 1 53 01 AM

### CODE REVIEW

**Comment by obycode** [comment]
I think that part that you changed here should stay as displaying the type. The problem that I was referring to was that the value was not shown below that: image

**Comment by shamim-io** [comment]
@obycode oh! My bad.. I understood it now. I will modify the PR.
Can you please provide me a transaction id by which i can test the same.

The above transaction id you have provided is showing as invalid.

**Comment by obycode** [comment]
Here's a new one: https://explorer.hiro.so/txid/0xef5e8eea8a1809b379eb6f5898183dbc47d88ca3bceec3039329e7d177c01d7b?chain=testnet

**Comment by shamim-io** [comment]
@obycode I have modified the PR. Kindly review it. 
Please do comment if there is any further modifications required. 
Thanks!

**Review by He1DAr — APPROVED** [review]

**Pull request merged**
