### PR TITLE
feat: signers

### PR DESCRIPTION
**Pull request by BLuEScioN**
Adds signers page. 
Figma file - https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=6378%3A8913&mode=dev

Currently using fake data. Waiting for the API to finish work on signers data endpoints. Slack context here https://hiropbc.slack.com/archives/C03UFUA5Q65/p1708373349155149

Work remaining:
- [ ] Add href to 
image
- [ ] Add API request for signers and staking information to power the signer table 
image
- [ ] Hook up the Voting Power Sort Filter with the Signer List
image
- [ ] Also use API request for signers and staking information to power Addresses Stacking header card
image

### CODE REVIEW

**Comment by andresgalante** [comment]
Great start!

Here are some things that I am seeing:

1- The figma has a 6-column grid where the first box takes 2 spaces. The implementation has a 5fr grid
image

2- Maybe we can build an example of a row with more than one address
image

**Comment by eugeniadigon** [comment]
Looks awesome @BLuEScioN ! I only have some minor UI/color comments:

**Top stats**
- [ ] Arrow: Can it be `green-600` / `green-500` when up, and `red-600` / `red-500` when down?
Screenshot 2024-02-22 at 15 21 06

- [ ] Progress bar colors: 
For Stacking cycle circle, can you please update the stroke width to `4px` and the slate color to `purple-200`? _(apologies for this as I changed it later in the design)_
Screenshot 2024-02-22 at 15 25 08

- In dark mode, this color should be different:
Screenshot 2024-02-22 at 15 25 14

---

**Table header tags**
- [ ] Replace text "`STX staked`" for "`STX stacked`"
- [ ] Font spacing: It looks more spaced in the implementation than in the design, I think it doesn't have the -1% letterspacing as set in the UI theme 

Screenshot 2024-02-22 at 15 10 44

---

**Table**
- [ ] The list starts at #0, I think it should start at 1
- [ ] Both Signer key and Address should have a hover underline (that'll link to Signer ID, and Address ID)
- [ ] Address font-color should be` slate-700` (light mode), `slate-600` (dark mode)
Screenshot 2024-02-22 at 15 16 36

- [ ] Would it be possible to center-align the first column? (rank numbers)
Screenshot 2024-02-22 at 15 18 38

- [ ] Would it be possible to have that first column sticky on mobile horizontal scroll?

---

**Comment by eugeniadigon** [comment]
For "See Stacking historical data", I think it's better to hide until we have a [Stacking page (WIP)](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6912%3A44150&mode=design&t=ugX9zJqd7j6NLhE8-1)

**Comment by BLuEScioN** [comment]
The list starts at #0, I think it should start at 1
 
 - I am using test data. This can be fixed when we are getting data from the API

Would it be possible to center-align the first column? (rank numbers)

- This can be done, yes, although it requires a bit of additional rework. I did not get to this fyi cc @He1DAr 

Would it be possible to have that first column sticky on mobile horizontal scroll?

- I think so. The work required for this would probably overlap with the work for "Would it be possible to center-align the first column? (rank numbers)". I also did not get to this fyi @He1DAr

**Pull request closed without merging**
