### PR TITLE
fix(regressions): fixed a couple bugs

### PR DESCRIPTION
**Pull request by BLuEScioN**
Fixes all bugs mentioned in this Slack thread https://hiropbc.slack.com/archives/C03TU42NL05/p1718708259862839

Biggest fix is for deleting networks.
It wasn't working before because removeCustomNetwork only tried to change customNetworks and not the other list of networks. 
It was confusing having 2 lists of networks, where one was customNetoworks, the other networks, which had networks with property isCustom. To simplify, I removed customNetworks and put everything in networks.
The other tricky thing here is we have to remember both added custom networks and removed custom networks. It's not sufficient to have just a customNetwork cookie. We need two cookies to handle both of these lists. Take for instance a situation where a user removes the old testnet network and adds the naka-1 network. The old testnet needs to initially show up for every user. However, I cannot put it into the added custom networks cookie because I cannot write code the initializes user cookies. Therefore, it will just show by default, unless the user deletes it, then it is added to the removed networks cookie. We then need the added custom networks cookie to track when the naka-1 network is added. These cookies to be kept in sync as well so as not to run into conflicts where a network is simultaneously in the added cookie and the removed cookie

### CODE REVIEW

**Review by PG650 — APPROVED** [review]

**Review by He1DAr — APPROVED** [review]

**Comment by eugeniadigon** [comment]
Fixes #1681, #1682

**Comment by eugeniadigon** [comment]
I still see the tiny icons bug on some pages: https://hiro-explorer-git-fix-regressions-blockstack.vercel.app/txid/SPQC38PW542EQJ5M11CR25P7BS1CA6QT4TBXGB3M.stableswap-stx-ststx-v-1-2?chain=mainnet# 

Screenshot 2024-06-24 at 13 52 36

**Comment by BLuEScioN** [comment]
> I still see the tiny icons bug on some pages: https://hiro-explorer-git-fix-regressions-blockstack.vercel.app/txid/SPQC38PW542EQJ5M11CR25P7BS1CA6QT4TBXGB3M.stableswap-stx-ststx-v-1-2?chain=mainnet#
> 
> Screenshot 2024-06-24 at 13 52 36

Thanks for pointing this out. I did not have an issue for this, so I did not know where to look for this

**Comment by eugeniadigon** [comment]
> > I still see the tiny icons bug on some pages: https://hiro-explorer-git-fix-regressions-blockstack.vercel.app/txid/SPQC38PW542EQJ5M11CR25P7BS1CA6QT4TBXGB3M.stableswap-stx-ststx-v-1-2?chain=mainnet#
> > Screenshot 2024-06-24 at 13 52 36
> 
> Thanks for pointing this out. I did not have an issue for this, so I did not know where to look for this

It was on the Slack message cited above, so I assumed it was part of this PR

**Pull request merged**
