### PR TITLE
feat: add stx price button to post conditions

### PR DESCRIPTION
**Pull request by shamim-io**
closes https://github.com/hirosystems/explorer/issues/1101

Closes Display dollar amount on Stacks tokens #1101 

Fixes issue:  Display dollar amount on Stacks tokens in post conditions

Feature details
Added StxPriceButton to post conditions

Feature image
Screenshot 2023-05-10 at 3 57 55 AM

Files changed
post-conditions.tsx
ContractCall/index.tsx

### CODE REVIEW

**Review by He1DAr — APPROVED** [review]

**Comment by He1DAr** [comment]
@shamim-io could you please look into this error:
image
Thank you so much!

**Comment by shamim-io** [comment]
@He1DAr I have modified the PR. We should not get this error again. Thanks!

**Comment by He1DAr** [comment]
Thank you for updating the PR!
I ran a few tests, and it seems like there's a small issue with the value passed to the price button. For example, if you check out this link: https://hiro-explorer-git-fork-shamim-io-feat-stxbutton-blockstack.vercel.app/txid/0xa38b0e9c953c4e5b2f7362fec881456c19160a33659aa6cf80e356d52ad281db?chain=mainnet)], you'll notice that the value isn't displaying the correct amount for the price button. It should reflect the $ amount of 2 STX.
Thanks again for your help! Let me know if you need any further information. 😊

**Comment by shamim-io** [comment]
@He1DAr I have passed the post condition amount to the button. Can you suggest which value shall I pass? 
If its post condition amount only, then I think we need to modify the value in the API response from backend. Correct me if i am wrong.

**Comment by He1DAr** [comment]
Hi @shamim-io!
The issue is caused by passing the value to `StxPriceButton` in stx instead of microStx. To fix this, you can pass `condition.amount` directly. That should do the trick!
```
{condition.type === 'stx' && <StxPriceButton tx={tx} value={Number(condition.amount)} />}
```
If you have any more questions, feel free to ask. Thank you for your patience in resolving the issue.

**Comment by shamim-io** [comment]
@He1DAr I have modified the condition. Sorry I solved it a bit late.

**Comment by shamim-io** [comment]
@He1DAr Even the above logic that you provided doesn't give the correct value. 
Screenshot 2023-06-15 at 11 48 29 PM

So apparently 8000STX ~ 4000 USD. 

Do we need to multiply the value by 100 as under: 
 `{condition.type === 'stx' && (
            <StxPriceButton tx={tx} value={Number(condition.amount) * 100} />
          )}`

**Comment by shamim-io** [comment]
@He1DAr Any thoughts on the above comment ? 🙂

**Comment by He1DAr** [comment]
Hi @shamim-io,
No need to multiple, the proposed solution should work.
image
image

**Comment by shamim-io** [comment]
@He1DAr I have made the changes. Sorry for the confusion. Fingers crossed :)

**Review by He1DAr — APPROVED** [review]
LGTM! Thank you @shamim-io

**Pull request merged**
